name: Build PHP binaries

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    name: Linux (PM ${{ matrix.pm-version-major }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        pm-version-major: [4, 5]

    steps:
      - uses: actions/checkout@v3

      - name: Install tools and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make autoconf automake libtool libtool-bin m4 wget libc-bin gzip bzip2 bison g++ git re2c libssh2-1 libssh2-1-dev php-redis

      - name: Compile PHP
        run: |
          # Used "set -ex" instead of hashbang since script isn't executed with hashbang
          set -ex
          trap "exit 1" ERR
          chmod 777 ./compile.sh
          ./compile.sh -t linux64 -j 4 -f -g -P ${{ matrix.pm-version-major }}

      - name: Create tarball
        run: tar -czf ./PHP_Linux-x86_64.tar.gz bin
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Linux-PM${{ matrix.pm-version-major }}
          path: |
            ./PHP_Linux-x86_64.tar.gz
            install.log
            compile.sh
          if-no-files-found: error

      - name: Prepare workspace for upload
        if: failure()
        run: tar -czf workspace.tar.gz install_data

      - name: Upload workspace
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Linux-workspace-PM${{ matrix.pm-version-major }}
          path: |
            workspace.tar.gz
          if-no-files-found: error

  macos:
    name: MacOS (PM ${{ matrix.pm-version-major }})
    runs-on: macos-11.0
    strategy:
      matrix:
        pm-version-major: [ 4, 5 ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Install tools and dependencies
        run: brew install libtool autoconf automake pkg-config bison re2c libssh php-redis
        
      - name: Compile PHP
        run: |
          export PATH="/usr/local/opt/bison/bin:$PATH"
          set -ex
          trap "exit 1" ERR
          chmod 777 ./compile.sh
          ./compile.sh -t mac-x86-64 -j4 -f -g -P ${{ matrix.pm-version-major }}
          
      - name: Create tarball
        run: tar -czf ./PHP_MacOS-x86_64.tar.gz bin
        
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: MacOS-PM${{ matrix.pm-version-major }}
          path: |
            ./PHP_MacOS-x86_64.tar.gz
            install.log
            compile.sh
          if-no-files-found: error

      - name: Prepare workspace for upload
        if: failure()
        run: tar -czf workspace.tar.gz install_data

      - name: Upload workspace
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: MacOS-workspace-PM${{ matrix.pm-version-major }}
          path: |
            workspace.tar.gz
          if-no-files-found: error